project:
  type: book

book:
  title: "The book of seahtrue"
  author: "Vincent de Boer"
  date: "16/12/2024"

  chapters:
    - index.qmd
    - part: jump.qmd
      chapters:
      - jump_intro.qmd
      - jump_essentials.qmd
      - jump_cars.qmd
      - jump_seahorse.qmd
      - jump_summary.qmd
    - part: swim.qmd
      chapters:
      - swim_functions.qmd
      - swim_outputs.qmd
      - swim_summary.qmd
    - part: dive.qmd
      chapters:
      - dive_alone.qmd
      - dive_together.qmd


  sidebar:
    search: true
    tools:
      - icon: github
        href: https://github.com/vcjdeboer

bibliography: references.bib

format:
  html:
    theme: cosmo
    link-external-icon: true
    link-external-newwindow: true
    include-in-header: _include/header.html
  pdf:
    documentclass: scrreprt

editor: visual

webr:
  packages: ['base']

filters:
  - webr


